# Generated by Django 4.1.7 on 2023-05-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='Profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
