# Generated by Django 4.1.7 on 2023-05-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userdb_cover_userdb_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='postsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posts', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Caption', models.CharField(blank=True, max_length=200, null=True)),
                ('Username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userapp.userdb')),
            ],
        ),
    ]
