# Generated by Django 4.1.7 on 2023-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_postsdb_username_alter_userdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
