# Generated by Django 4.1.7 on 2023-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_postsdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsdb',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postsdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
