# Generated by Django 4.1.7 on 2023-05-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_postsdb_name_alter_postsdb_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsdb',
            name='Name',
        ),
    ]
