# Generated by Django 4.1.7 on 2023-05-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_postsdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsdb',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userdb'),
        ),
    ]
