# Generated by Django 4.1.7 on 2023-05-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_postsdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
