# Generated by Django 4.1.7 on 2023-05-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_postsdb_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsdb',
            name='Username',
        ),
    ]
