# Generated by Django 4.1.7 on 2023-05-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_postsdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsdb',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userdb'),
        ),
    ]
