# Generated by Django 4.1.7 on 2023-05-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_followersdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userdb')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.postsdb')),
            ],
        ),
    ]
