# Generated by Django 4.1.7 on 2023-05-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsdb',
            name='no_of_like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
