# Generated by Django 4.1.7 on 2023-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_likes_username_alter_likes_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsdb',
            name='no_of_like',
            field=models.IntegerField(default=0),
        ),
    ]
