# Generated by Django 4.1.7 on 2023-05-30 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_alter_postsdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsdb',
            name='post_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postsdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
