# Generated by Django 4.1.7 on 2023-06-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_remove_postsdb_l_status_postsdb_l_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userdb')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.postsdb')),
            ],
        ),
    ]
