# Generated by Django 4.1.7 on 2023-06-15 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_commentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdb',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
